<?php

namespace App;

use App\Scopes\BuyerScope;
use App\Transformers\BuyerTransformer;
use Illuminate\Database\Eloquent\Model;

/**
 * @method static has(string $string)
 * @method static findOrFail(int $id)
 * @property mixed transactions
 * @property mixed created_at
 * @property mixed updated_at
 */
class Buyer extends User
{

    public $transformer = BuyerTransformer::class;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new BuyerScope);
    }

    public function transactions() {
        return $this->hasMany(Transaction::class);
    }
}
